### ISSUE TITLE
Game crashes when editing trades

### ISSUE THREAD

**Issue by tigwex** [samolego/TraderNPCs#18]
Saw someone else bring this up but they never followed up. Using Taterzens 1.9.6 and TraderNPCs 1.1.1, here's the error it threw, any ideas what's causing it?

[01:53:51] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/samo_lego/taterzens/fabric/gui/ListItemsGUI
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.14.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.samo_lego.tradernpcs.gui.TradeMenuGUI.lambda$new$0(TradeMenuGUI.java:27) ~[tradernpcs-1.1.1-fabric(3).jar:?]
	at eu.pb4.sgui.api.elements.GuiElementInterface$ItemClickCallback.click(GuiElementInterface.java:91) ~[sgui-1.0.0+1.18.1-3f088ed1c170710d.jar:?]
	at eu.pb4.sgui.api.gui.SlotGuiInterface.click(SlotGuiInterface.java:31) ~[sgui-1.0.0+1.18.1-3f088ed1c170710d.jar:?]
	at net.minecraft.class_3244.handler$bpb000$sgui_handleGuiClicks(class_3244.java:5726) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12076(class_3244.java:1413) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_12191(class_2813.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_11054(class_2813.java:13) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.samo_lego.taterzens.fabric.gui.ListItemsGUI
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.14.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 29 more

**Comment by samolego** [comment]
Oh, you're using incompatible version combo :\

**Comment by tigwex** [comment]
Oh nodding, that makes sense! Ty, will change it out :)
