### ISSUE TITLE
1.18.2 Forge Missing Dependency

### ISSUE THREAD

**Issue by mfventura** [samolego/TraderNPCs#9]
**Describe the bug**
Crash when trying to access to the Trader Menu.
Check additional information please.

**Platform(s)**

- [x] Forge

**Environment(s)**

- [x] Server

**Versions**
* Minecraft 1.18.2
* Taterzens 1.9.6
* TraderNPC 1.1.0 forge

**To Reproduce**
1. Launch server and client both with mods installeds (see versions)
2. User as OP
3. Command ingame -> /npc create VillagerTrader
4. Command ingame -> /npc edit professions add tradernpcs:trader
5. Command ingame -> /npc deselect
7. Right click on the NPC

**Expected behavior**
Not a crash and server shutdown

**Logs**

<details>
  <summary>Logs</summary>
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12/7/22 18:41
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: eu/pb4/sgui/api/gui/MerchantGui
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at org.samo_lego.tradernpcs.profession.TraderNPCProfession.interactAt(TraderNPCProfession.java:31) ~[tradernpcs-1.1.0-forge.jar%2361!/:?] {re:classloading}
	at org.samo_lego.taterzens.npc.TaterzenNPC.m_6071_(TaterzenNPC.java:1094) ~[taterzens-1.9.6-forge.jar%2359!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.Mob.m_6096_(Mob.java:1051) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.player.Player.m_36157_(Player.java:968) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:taterzens.common.mixins.json:accessors.PlayerAccessor,pl:mixin:APP:taterzens.common.mixins.json:player.PlayerMixin_PeacefulDamage,pl:mixin:APP:disguiselib.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:byg.mixins.json:common.entity.MixinPlayer,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_143678_(ServerGamePacketListenerImpl.java:1228) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,re:classloading,pl:mixin:APP:disguiselib.mixins.json:ServerPlayNetworkHandlerMixin_HitCheck,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_142299_(ServerGamePacketListenerImpl.java:1240) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,re:classloading,pl:mixin:APP:disguiselib.mixins.json:ServerPlayNetworkHandlerMixin_HitCheck,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.m_142457_(ServerboundInteractPacket.java:116) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_179617_(ServerboundInteractPacket.java:66) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6946_(ServerGamePacketListenerImpl.java:1224) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:53) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:13) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2367!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
Caused by: java.lang.ClassNotFoundException: eu.pb4.sgui.api.gui.MerchantGui
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 33 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.15.0-41-generic
	Java Version: 17.0.3, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 372622600 bytes (355 MiB) / 1029701632 bytes (982 MiB) up to 1029701632 bytes (982 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3,60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: SVGA II Adapter
	Graphics card #0 vendor: VMware (0x15ad)
	Graphics card #0 VRAM (MB): 16,00
	Graphics card #0 deviceId: 0x0405
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4836,62
	Virtual memory used (MB): 1832,45
	Swap memory total (MB): 2874,00
	Swap memory used (MB): 0,00
	JVM Flags: 0 total; 
	Server Running: true
	Player Count: 1 / 20; [ServerPlayer['Fancoz'/117, l='ServerLevel[world]', x=-6.66, y=64.00, z=-180.53]]
	Data Packs: vanilla, mod:voicechat (incompatible), mod:terrablender (incompatible), mod:taterzens (incompatible), mod:jei (incompatible), mod:disguiselib (incompatible), mod:wthit (incompatible), mod:casinocraft, mod:sophisticatedcore (incompatible), mod:curios (incompatible), mod:collective, mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:world_pre_generator, mod:configured (incompatible), mod:badpackets (incompatible), mod:worldborder, mod:lucky77 (incompatible), mod:sophisticatedbackpacks (incompatible), mod:architectury (incompatible), mod:ftblibrary (incompatible), mod:byg (incompatible), mod:carryon (incompatible), mod:ftbteams (incompatible), mod:ftbchunks (incompatible), mod:forge, mod:appleskin (incompatible), mod:expandability (incompatible), mod:tradernpcs (incompatible)
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.18.2-2.2.49.jar                 |Simple Voice Chat             |voicechat                     |1.18.2-2.2.49       |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.1.0.102.jar           |TerraBlender                  |terrablender                  |1.18.2-1.1.0.102    |DONE      |Manifest: NOSIGNATURE
		taterzens-1.9.6-forge.jar                         |Taterzens                     |taterzens                     |1.9.6               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.0.209.jar                          |Just Enough Items             |jei                           |9.7.0.209           |DONE      |Manifest: NOSIGNATURE
		disguiselib-1.2.2-forge.jar                       |DisguiseLib                   |disguiselib                   |1.2.2               |DONE      |Manifest: NOSIGNATURE
		wthit-forge-4.11.0.jar                            |wthit                         |wthit                         |4.11.0              |DONE      |Manifest: NOSIGNATURE
		tradernpcs-1.1.0-forge.jar                        |Trader NPCs                   |tradernpcs                    |1.1.0               |DONE      |Manifest: NOSIGNATURE
		CasinoCraft_1.18.2_v17.jar                        |CasinoCraft                   |casinocraft                   |17.0                |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.18.2-0.3.7.59.jar             |Sophisticated Core            |sophisticatedcore             |1.18.2-0.3.7.59     |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |DONE      |Manifest: NOSIGNATURE
		collective-1.18.2-4.28.jar                        |Collective                    |collective                    |4.28                |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              |DONE      |Manifest: NOSIGNATURE
		WorldPreGenerator-1.18.2-2.0.1.jar                |World Pre Generator           |world_pre_generator           |2.0.1               |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.18.2.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		badpackets-forge-0.1.2.jar                        |Bad Packets API               |badpackets                    |0.1.2               |DONE      |Manifest: NOSIGNATURE
		worldborder_1.18.2-2.6.jar                        |World Border                  |worldborder                   |2.6                 |DONE      |Manifest: NOSIGNATURE
		Lucky77_1.18.2_v02.jar                            |Lucky77                       |lucky77                       |2.0                 |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.2-3.17.10.621.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.17.10.621  |DONE      |Manifest: NOSIGNATURE
		architectury-4.5.76-forge.jar                     |Architectury                  |architectury                  |4.5.76              |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1802.3.6-build.123.jar          |FTB Library                   |ftblibrary                    |1802.3.6-build.123  |DONE      |Manifest: NOSIGNATURE
		Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.2.jar    |Oh The Biomes You'll Go       |byg                           |1.4                 |DONE      |Manifest: NOSIGNATURE
		carryon-1.18.2-1.17.0.8.jar                       |Carry On                      |carryon                       |1.17.0.8            |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-1802.2.6-build.51.jar             |FTB Teams                     |ftbteams                      |1802.2.6-build.51   |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-forge-1802.3.6-build.145.jar           |FTB Chunks                    |ftbchunks                     |1802.3.6-build.145  |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.60-universal.jar                |Forge                         |forge                         |40.1.60             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.18-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.18        |DONE      |Manifest: NOSIGNATURE
		expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 7813aa4d-4814-495b-a88d-4c4ae88a5c06
	FML: 40.1
	Forge: net.minecraftforge:40.1.60
</details>

**Additional context**
I checked the libraries folder, there's no "eu" folder. So probably there's a missing dependency.
I tried to add it by my self getting the jar from https://github.com/Patbox/sgui but it doesnt works, maybe i didnt that step good.

I checked your comments: https://www.curseforge.com/minecraft/mc-mods/tradernpcs#forum-post-body-32
you didnt released a 1.18.2 version because it seems to dont be bugs. There's one.

**Comment by samolego** [comment]
I've spent days on gradle trying to get it to work (the code works, mod works in developing environment but not in production).
The time spent on this hugely affects my motivation, I'm not even sure if I'll maintain forge version :(.

**Comment by mfventura** [comment]
dont worry, thank you so much for your time ^^
